### ISSUE TITLE
Add a continuous integration engine (puppet pipeline is diserable)

### ISSUE THREAD

**Issue by ramonsaraiva** [ramonsaraiva/django-expiry#4]

**Comment by AhmedRedaAmin** [comment]
Would you be interested in Travis CI ?
Also , worth mentioning that distelli was bought by Puppet and is now Puppet pipeline

**Comment by ramonsaraiva** [comment]
Edited the title :-) I think that either CircleCI or Puppet then, cause I have 0 experience on Travis.

**Comment by AhmedRedaAmin** [comment]
Alright , I am quite the opposite , but to be able to consult you if I get stuck I'll read up on circle CI , wish me luck :smile:

**Comment by AhmedRedaAmin** [comment]
Hey Ramon !  I 'll be taking a few days hiatus  , if you don't mind . Circle CI uses YAML and build techniques very close to Travis so I hope it will be very close to what I 'm used to , gotta disappear for a couple of days though , don't check my fork as most what I'm trying to do is still local , however , I hope I'll be back to it ASAP , sorry man , I wanted to finish it maximum by tomorrow but I really got caught up in something , just wanted to keep you updated .
See you soon , mate .

**Comment by ramonsaraiva** [comment]
No worries, take your time.

**Comment by AhmedRedaAmin** [comment]
hey @ramonsaraiva ! Do you have a moment to help me explain some behavior in CircleCI ?
EDIT : yeah , it was just confirmed [here](https://discuss.circleci.com/t/dont-try-to-manage-virtualenvs/3411)
Both poetry and Circle CI overwrite each others python virtual environments .
Not sure how to work around this :disappointed:  
For your reference , here is where it is failing 
![selection_066](https://user-images.githubusercontent.com/17142710/46894413-af74dd80-ce74-11e8-8d66-f8a93be1be7f.png)


EDIT : Solved , the problem here is using sudo which causes the poetry to setup virtualenv in a different path than the circleCI , them overwriting each other doesn't affect the dependencies it appears , the two virtual environments seem to see each other rather than overwrite each other , or maybe they get merged , not sure really .
